# -*- coding: utf-8 -*-
"""plots_SarriaAlejandra_resorteS8CASA_EDO2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1STGpqvQL1Yu10Wzn_ktCQl44VUjD0UWO
"""

import numpy as np
import matplotlib.pyplot as plt
import math

datEuler_2 = np.genfromtxt("euler_2.dat", delimiter=",");
plt.plot(datEuler_2[1:-1,0], datEuler_2[1:-1,1])
plt.savefig("euler.pdf")
plt.show()

datLeap_2 = np.genfromtxt("leapfrog_2.dat", delimiter=",");
plt.plot(datLeap_2[1:-1,0], datLeap_2[1:-1,1])
plt.savefig("leapfrog.pdf")
plt.show()

datRun_2 = np.genfromtxt("rungekutta_2.dat", delimiter=",");
plt.plot(datRun_2[1:-1,0], datRun_2[1:-1,1])
plt.savefig("rungekutta.pdf")
plt.show()