# -*- coding: utf-8 -*-
"""PLOTS_SarriaAlejandra_S8planetasCASA_EDO2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpvoE8VBdy1eQSArfISpkAAj_mtMwgex
"""

import numpy as np
import matplotlib.pyplot as plt
import math

datEulerOrbit = np.genfromtxt("EulerPlanetas.dat", delimiter=",");
plt.plot(datEulerOrbit[1:-1,1], datEulerOrbit[1:-1,2])
plt.savefig("EulerOrbit.pdf")
plt.show()

datLeapfrogOrbit = np.genfromtxt("LeapfrogPlanetas.dat", delimiter=",");
plt.plot(datLeapfrogOrbit[1:-1,1], datLeapfrogOrbit[1:-1,2])
plt.savefig("LeapfrogOrbit.pdf")
plt.show()